//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class company:head_office
    {
        public int com_id { get; set; }
        public string com_name { get; set; }
        public string com_size { get; set; }
        public string work_address { get; set; }
        public new int head_id { get; set; }

        public int b_count { get; set; }
        
    }
}
