//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class deparment:company
    {
        public int b_id { get; set; }
        public string b_name { get; set; }
        public string b_work_name { get; set; }
        public string b_work_desc { get; set; }
        public new int com_id { get; set; }
        public int c_count { get; set; }
    }
}
