//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class filelist
    {
        public int id { get; set; }
        public string title { get; set; }
        public string img { get; set; }
        public string filepath { get; set; }
        public int updatetime { get; set; }
        public string types { get; set; }
        public int loaduser { get; set; }
        public int studenttime { get; set; }
        public int head_id { get; set; }
        public int filetype { get; set; }//文件类型 0 普通文件 1三级教育文件
        public int jibie { get; set; }//文件的级别 0未选择 1厂级 2 部门车门级 3 班组级
    }
}
