//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_up
    {
        public int m_id { get; set; }
        public string m_no { get; set; }
        public string m_title { get; set; }
        public string m_desc { get; set; }
        public string m_file { get; set; }
        public int to_user { get; set; }
        public int from_user { get; set; }
        public int mc_id { get; set; }
    }
}
