//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class read_message_up:msg_classify
    {
        public int id { get; set; }
        public int us_id { get; set; }
        public int m_id { get; set; }
        public int read_time { get; set; }
        public string read_over { get; set; }
        public int read_pass { get; set; }
        public int pass_time { get; set; }
    }
}
