//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_classify
    {
        public int id { get; set; }
        public string t_name { get; set; }
        public int create_time { get; set; }
        public int us_id { get; set; }
        public int head_id { get; set; }
        public int type_a { get; set; }
        public int type_b { get; set; }
        public int type_c { get; set; }
        public int type_d { get; set; }
        public int is_send { get; set; }
        public int defen_a { get; set; }
        public int defen_b { get; set; }
        public int defen_c { get; set; }
        public int defen_d { get; set; }
        public int t_types { get; set; }


    }
}
