//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public class user_detail:users
    {
        public new int us_id { get; set; }
        public int gender { get; set; }
        public int age { get; set; }
        public string us_no { get; set; }
        public string mobile { get; set; }
        public string tel { get; set; }
        public int work_state { get; set; }
        public string position { get; set; }
        public new int head_id { get; set; }
        public new int com_id { get; set; }
        public new int b_id { get; set; }
        public new int c_id { get; set; }
        public int verify { get; set; }
        public long count { get; set; }


        public user_detail SetData(dynamic data)
        {
            us_id = data.us_id != null ? Convert.ToInt32(data.us_id) : 0;
            login_name = data.login_name != null ? data.login_name : "";
            login_pwd = data.login_pwd != null ? data.login_pwd : "";
            real_name = data.real_name != null ? data.real_name : "";
            gender = data.gender != null ?Convert.ToInt32(data.gender) : 0;
            age = data.age != null ? Zh.Tool.Date_Tool.TimeToInt(data.age) : 0;
            us_no = data.us_no != null ? data.us_no : "";
            mobile = data.mobile != null ? data.mobile : "";
            tel = data.tel != null ? data.tel : "";
            work_state = data.work_state != null ? Convert.ToInt32(data.work_state) : 0;
            position = data.position != null ? data.position : "";
            head_id = data.head_id != null ? Convert.ToInt32(data.head_id) : 0;
            com_id = data.com_id != null ? Convert.ToInt32(data.com_id) : 0;
            b_id = data.b_id != null ? Convert.ToInt32(data.b_id) : 0;
            c_id = data.c_id != null ? Convert.ToInt32(data.c_id) : 0;
            verify = data.verify != null ? Convert.ToInt32(data.verify) : 0;
            head_name = data.head_name != null ? data.head_name : "";
            head_size = data.head_size != null ? data.head_size : "";
            head_address = data.head_address != null ? data.head_address : "";
            head_logo = data.head_logo != null ? data.head_logo : "";
            
            c_name = data.c_name != null ? data.c_name : "";
            c_work_name = data.c_work_name != null ? data.c_work_name : "";
            c_work_desc = data.c_work_desc != null ? data.c_work_desc : "";
            b_name = data.b_name != null ? data.b_name : "";
            b_work_name = data.b_work_name != null ? data.b_work_name : "";
            b_work_desc = data.b_work_desc != null ? data.b_work_desc : "";
            com_name = data.com_name != null ? data.com_name : "";
            com_size = data.com_size != null ? data.com_size : "";
            work_address = data.work_address != null ? data.work_address : "";
            return this;
        }
    }


}
