//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yhtable
    {
        public int y_id { get; set; }
        public string y_name { get; set; }
        public int y_createtime { get; set; }
        public string y_body { get; set; }
        public string y_area { get; set; }
        public string y_type { get; set; }
        public int y_dengji { get; set; }
        public string y_desc { get; set; }
        public string y_img1 { get; set; }
        public int y_endtime { get; set; }
        public int y_usid { get; set; }
        public int y_zguser { get; set; }
        public string y_yaoqiu { get; set; }
        public int y_headuser { get; set; }
        public int y_headtype { get; set; }
        public string y_zgdesc { get; set; }
        public int y_zgtime { get; set; }
        public string y_qrdesc { get; set; }
        public string y_qrimg { get; set; }
        public int y_status { get; set; }
        public int y_qruser { get; set; }
        public int y_qrtime { get; set; }
        public int y_headid { get; set; }
        public string y_no { get; set; }
        public string y_zgimg { get; set; }

        /// <summary>
        /// 检查人姓名
        /// </summary>
        public string jiancha_name { get; set; }
        public string head_username { get; set; }//检查部门负责人姓名
        public string zhenggai_name { get; set; }//整改人姓名
        public string queren_name { get; set; }//确认人姓名


        public yhtable SetData(dynamic data)
        {
            y_name = data.y_name != null ? data.y_name : "";
            y_createtime = data.y_createtime != null ? Zh.Tool.Date_Tool.TimeToInt(data.y_createtime) : Zh.Tool.Date_Tool.TimeToInt(DateTime.Now);
            y_body = data.y_body != null ? data.y_body : "";
            y_area = data.y_area != null ? data.y_area : "";
            y_type = data.y_type != null ? data.y_type : "";
            y_dengji = data.y_dengji != null ? Convert.ToInt32(data.y_dengji) : 0;
            y_desc = data.y_desc != null ? data.y_desc : "";
            y_img1 = data.y_img1 != null ? data.y_img1 : "";
            y_endtime = data.y_endtime != null ? Zh.Tool.Date_Tool.TimeToInt(data.y_endtime) : Zh.Tool.Date_Tool.TimeToInt(DateTime.Now);
            y_usid = data.y_usid != null ? Convert.ToInt32(data.y_usid) : 0;
            y_zguser = data.y_zguser != null ? Convert.ToInt32(data.y_zguser) : 0;
            y_yaoqiu = data.y_yaoqiu != null ? data.y_yaoqiu : "";
            y_headuser = data.y_headuser != null ? Convert.ToInt32(data.y_headuser) : 0;
            y_headtype = data.y_headtype != null ? Convert.ToInt32(data.y_headtype) : 0;
            y_zgdesc = data.y_zgdesc != null ? data.y_zgdesc : "";
            y_zgtime = data.y_zgtime != null ? Zh.Tool.Date_Tool.TimeToInt(data.y_zgtime) : Zh.Tool.Date_Tool.TimeToInt(DateTime.Now);
            y_qrdesc = data.y_qrdesc != null ? data.y_qrdesc : "";
            y_qrimg = data.y_qrimg != null ? data.y_qrimg : "";
            y_status = data.y_status != null ? Convert.ToInt32(data.y_status) : 0;
            y_qruser = data.y_qruser != null ? Convert.ToInt32(data.y_qruser):0;
            y_qrtime = data.y_qrimg != null ? Zh.Tool.Date_Tool.TimeToInt(data.y_qrtime) : Zh.Tool.Date_Tool.TimeToInt(DateTime.Now);
            y_headid = data.y_headid != null ? Convert.ToInt32(data.y_headid) : 0;
            y_no = data.y_no != null ? data.y_no : "";
            y_zgimg = data.y_zgimg != null ? data.y_zgimg : "";
            return this;
        }

        
    }
}
