//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yinhuan
    {
        public int yh_id { get; set; }
        public string yh_no { get; set; }
        public string yh_applicationName { get; set; }
        public int yh_create_time { get; set; }
        public string yh_body { get; set; }
        public string yh_area { get; set; }
        public string yh_type { get; set; }
        public int yh_dengji { get; set; }
        public string yh_desc { get; set; }
        public string yh_img { get; set; }
        public string yh_imgodd { get; set; }
        public int yh_timestart { get; set; }
        public int yh_timeend { get; set; }
        //检查人
        public int yh_user_from { get; set; }
        public string yh_user_from_name { get; set; }

        //签发部门
        public int yh_deparment { get; set; }
        public string yh_deparment_name { get; set; }

        //受检部门
        public int yh_to_deparment { get; set; }
        public string yh_to_deparment_name { get; set; }

        public string yh_yaoqiu { get; set; }
        //实施负责人
        public int yh_to_user { get; set; }
        public string yh_to_user_name { get; set; }


        public int yh_shishi_time { get; set; }
        public string yh_zhenggaihou { get; set; }

        //整改确认人
        public int yh_queren_user { get; set; }
        public string yh_queren_user_name { get; set; }


        public int yh_queren_time { get; set; }
        public int yh_send_state { get; set; }
    }

    
}
