//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT_API.Controllers.GDT.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class yinhuan_down:yinhuan_up
    {
        public int yh_downid { get; set; }
        public new string yh_no { get; set; }
        public int yh_to_userdown { get; set; }
        public new int yh_state { get; set; }
        public new int yh_time { get; set; }

        public yinhuan_down SetData(dynamic data)
        {
            this.yh_no = data.yh_no != null ? data.yh_no : "";
            this.yh_state = data.yh_state != null ? Convert.ToInt32(data.yh_state) : 0;
            this.yh_to_userdown = data.yh_to_users != null ? Convert.ToInt32(data.yh_to_userdown) : 0;
            this.yh_time = data.yh_time != null&&data.yh_time!="" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_time) : 0;
            this.yh_to_userup = data.yh_to_userup != null ? Convert.ToInt32(data.yh_to_userup) : 0;


            //string
            this.yh_applicationName = data.yh_applicationName != null ? data.yh_applicationName : "";
            this.yh_body = data.yh_body != null ? data.yh_body : "";
            this.yh_area = data.yh_area != null ? data.yh_area : "";
            this.yh_type = data.yh_type != null ? data.yh_type : "";
            this.yh_desc = data.yh_desc != null ? data.yh_desc : "";
            this.yh_img = data.yh_img != null ? data.yh_img : "";
            this.yh_imgodd = data.yh_imgodd != null ? data.yh_imgodd : "";
            this.yh_yaoqiu = data.yh_yaoqiu != null ? data.yh_yaoqiu : "";
            this.yh_zhenggaihou = data.yh_zhenggaihou != null ? data.yh_zhenggaihou : "";
            //int
            this.yh_create_time = data.yh_create_time != null&& data.yh_create_time != "" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_create_time) : 0;
            this.yh_dengji = data.yh_dengji != null ? Convert.ToInt32(data.yh_dengji) : 0;
            this.yh_timestart = data.yh_timestart != null&& data.yh_timestart!="" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_timestart) : 0;
            this.yh_timeend = data.yh_timeend != null&& data.yh_timeend!="" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_timeend) : 0;
            this.yh_user_from = data.yh_user_from != null ? Convert.ToInt32(data.yh_user_from) : 0;
            this.yh_deparment = data.yh_deparment != null ? Convert.ToInt32(data.yh_deparment) : 0;
            this.yh_to_deparment = data.yh_to_deparment != null ? Convert.ToInt32(data.yh_to_deparment) : 0;
            this.yh_to_user = data.yh_to_user != null ? Convert.ToInt32(data.yh_to_user) : 0;
            this.yh_shishi_time = data.yh_shishi_time != null&& data.yh_shishi_time!="" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_shishi_time) : 0;
            this.yh_queren_user = data.yh_queren_user != null ? Convert.ToInt32(data.yh_queren_user) : 0;
            this.yh_queren_time = data.yh_queren_time != null&& data.yh_queren_time != "" ? Zh.Tool.Date_Tool.TimeToInt(data.yh_queren_time) : 0;
            this.yh_send_state = data.yh_send_state != null ? Convert.ToInt32(data.yh_send_state) : 0;
            return this;
        }
    }
}
