//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class yhtable
    {
        public int y_id { get; set; }
        public string y_name { get; set; }
        public int y_createtime { get; set; }
        public string y_body { get; set; }
        public string y_area { get; set; }
        public string y_type { get; set; }
        public int y_dengji { get; set; }
        public string y_desc { get; set; }
        public string y_img1 { get; set; }
        public int y_endtime { get; set; }
        public int y_usid { get; set; }
        public int y_zguser { get; set; }
        public string y_yaoqiu { get; set; }
        public int y_headuser { get; set; }
        public int y_headtype { get; set; }
        public string y_zgdesc { get; set; }
        public int y_zgtime { get; set; }
        public string y_qrdesc { get; set; }
        public string y_qrimg { get; set; }
        public int y_status { get; set; }
        public int y_qruser { get; set; }
        public int y_qrtime { get; set; }
    }
}
